### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by hongchangwu** [johnwhitington/ppx_blob#14]
The latest published version still depends on jbuilder. Can you publish a new version that uses dune? Thanks.

**Comment by johnwhitington** [comment]
It looks like someone has already fixed the source to use Dune, so we just need to update the OPAM package? Is that what you want?

**Comment by hongchangwu** [comment]
@johnwhitington yup

**Comment by johnwhitington** [comment]
@Leonidas-from-XIV are you happy for me to tag this repository with a new version number and push a new version of the OPAM package? Is it in a good state?

**Comment by Leonidas-from-XIV** [comment]
@johnwhitington I think it might be good to go, though personally I would replace `topkg` with `dune-release`. So if you want I can shoot you a quick PR for that too.

**Comment by johnwhitington** [comment]
@Leonidas-from-XIV Yes, please. I don't keep up with build systems, so I defer to your judgement.

**Comment by Leonidas-from-XIV** [comment]
@johnwhitington Fair enough, the changes are minuscule anyway; submitted as #15.

**Comment by johnwhitington** [comment]
Ok, merged. Thanks! I will do an OPAM release in the next few days.

**Comment by johnwhitington** [comment]
Alright, I have had go at making a new release with dune-release, but my complete lack of knowledge of dune / dune-release isn't helping. I am stuck at `dune-release distrib` with:

```
gorge:ppx_blob john$ dune-release distrib
[-] Building source archive
Error: The project name is not defined, please add a (name <name>) field to
your dune-project file.
dune-release: [ERROR] run ['dune' 'subst']: exited with 1
```

(I have added such a field to dune-project....)

Any ideas?

**Comment by Leonidas-from-XIV** [comment]
@johnwhitington Okay, I made #16 to fix another failure. You need to commit all of these, use `make tag` to tell dune release to take the current `HEAD` and mark it as `0.5`. Then `make distrib` will build a tarball, unpack it, build it and test it. This should now succeed. Then `make publish` should take all of the artifacts and upload them to github. `git push` might be useful afterwards to push the tags.

`dune-release opam pkg` is then able to generate an `opam` file with the proper URLs and checksums, that can be submitted to opam-repository. It is generated somewhere in `_build`, e.g. `_build/ppx_blob.0.5/...`.

**Comment by johnwhitington** [comment]
Thanks. `make distrib` now works. Here's the error from `make publish`:

```
dune-release publish
[-] Publishing documentation
[-] Selected packages: ppx_blob
[-] Generating documentation from _build/ppx_blob-0.6-1-gac7a9c1.tbz
[-] Publishing to github
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
[-] Creating new gh-pages branch with inital commit on johnwhitington/ppx_blob
[-] Updating local gh-pages branch
[?] Push new documentation to git@github.com:johnwhitington/ppx_blob.git#gh-pages? [Y/n]
Y
[-] Pushing new documentation to git@github.com:johnwhitington/ppx_blob.git#gh-pages
dune-release: [ERROR] run ['git' '--git-dir' '.git' 'push'
                           'git@github.com:johnwhitington/ppx_blob.git'
                      'gh-pages:gh-pages']: exited with 128
make: *** [publish] Error 3
```

**Comment by Leonidas-from-XIV** [comment]
Hmm, what happens if you run that git command manually? Maybe it is because there is no `gh-pages` branch.

**Comment by johnwhitington** [comment]
This:

```
gorge:ppx_blob john$ git --git-dir .git push git@github.com:johnwhitington/ppx_blob.git gh-pages:gh-pages
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

(I have no problem with `git push` otherwise). Something to do with gh-pages? Maybe I need to initialise something?

**Comment by bbc2** [comment]
If the GitHub pages are not necessary, maybe they could be skipped?  If that doesn't work, I would be happy to assist with the maintenance.  This package is very useful for me and others.

**Comment by Leonidas-from-XIV** [comment]
Maybe you're usually pushing through HTTPS and this command uses SSH?

**Comment by johnwhitington** [comment]
@bbc2 are you happy to take ownership of the repository, so you can have a go at it? None of this is within my area of expertise. I wrote ppx_blob in a couple of hours a few years ago, when PPX first came out, as a little toy, and I really don't understand most of the contents of this repository now...

**Comment by bbc2** [comment]
Sure I would be happy to.

**Comment by bbc2** [comment]
PR at opam-repository: https://github.com/ocaml/opam-repository/pull/15923.

@johnwhitington dune-release successfully pushed to the `gh-pages` branch but it looks like GitHub pages are disabled for the repository.  I think there's a repository setting to enable it but I don't have access.  It's not critical though.

**Comment by johnwhitington** [comment]
It claims to be enabled. Here's a screenshot, together with the contents of the menu:

https://www.coherentpdf.com/tmp/ghpages.png

(This is how I found it; I have not changed anything)

**Comment by bbc2** [comment]
OK then that's a mystery to me :)

**Comment by Leonidas-from-XIV** [comment]
I've reached out to GitHub support about this once and was told that to make gh-pages work, the repository owner needs to push to it once (a single time suffices). I assume this is to ensure the owner knows gh-pages exists, but it is a bit of a strange rule.

**Comment by johnwhitington** [comment]
Thanks for that. My git knowledge is pretty limited, but here's what I tried, without luck:

```
gorge:ppx_blob john$ git pull
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 1), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/johnwhitington/ppx_blob
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new tag]         0.6.0      -> 0.6.0
Already up-to-date.

gorge:ppx_blob john$ git commit --allow-empty
[gh-pages 38b915d] Empty commit to satisfy GitHub

gorge:ppx_blob john$ git push
fatal: The current branch gh-pages has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin gh-pages

gorge:ppx_blob john$ git push --set-upstream origin gh-pages
To https://github.com/johnwhitington/ppx_blob.git
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'https://github.com/johnwhitington/ppx_blob.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

gorge:ppx_blob john$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> gh-pages

gorge:ppx_blob john$ git pull origin gh-pages
From https://github.com/johnwhitington/ppx_blob
 * branch            gh-pages   -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

Any pointers?

**Comment by Leonidas-from-XIV** [comment]
I am not 100% sure but it seems like your local `gh-pages` branch is in a weird state and debugging that might be tricky. As a quick and dirty solution, it might be faster to just use a second clone of the `ppx_blob` repository, since you only need to push a single commit:

```
cd /tmp
git clone git@github.com:johnwhitington/ppx_blob.git
cd ppx_blob
git checkout gh-pages
git commit --allow-empty
git push origin gh-pages
```

**Comment by johnwhitington** [comment]
Done. Thanks!

**Comment by Leonidas-from-XIV** [comment]
Nice, [here's a link to the generated documentation](https://johnwhitington.github.io/ppx_blob/).
