### ISSUE TITLE
let-operator compatible release

### ISSUE THREAD

**Issue by hcarty** [johnwhitington/ppx_blob#18]
Would you have time to make a new release?  I'm pinned to the latest (as of this writing) `master` commit locally for now.

**Comment by johnwhitington** [comment]
There was a new release only a few days ago, so I don't know if this is likely, but pinging @Leonidas-from-XIV just in case.

**Comment by bbc2** [comment]
I can make a 0.7.0 release.  Sounds good?

**Comment by hcarty** [comment]
Thank you @bbc2

**Comment by bbc2** [comment]
New version submitted: https://github.com/ocaml/opam-repository/pull/16067.
