### ISSUE TITLE
Not compatible with 4.03

### ISSUE THREAD

**Issue by aantron** [johnwhitington/ppx_blob#2]
Due to usage of `Const_string`, which in 4.03 is replaced by `Pconst_string` (and perhaps other minor differences).

I would submit a PR, but do you prefer:
- depending on `ppx_tools`, which has an `Ast_convenience` module (in part for) dealing with this sort of thing, or
- maintaining two branches, one for 4.03+, and one for 4.02?

**Comment by johnwhitington** [comment]
Depending on ppx_tools is clearly better, I think. A PR would be much appreciated.
