### ISSUE TITLE
ppx_blob and the compilation chain

### ISSUE THREAD

**Issue by pveber** [johnwhitington/ppx_blob#5]
When using `ppx_blob`, the compilation chain has to know the included file is now a dependency of the file that includes it (so that the including file gets recompiled when the included file is modified). Is there another means than tagging dependencies manually?

**Comment by johnwhitington** [comment]
I'm afraid I don't know much about build systems at all. I presume you think this is a problem for all ppx_ items, not just ppx_blob? If so, the mantis tracker or the mailing list might be the best place to get an answer.

**Comment by pveber** [comment]
On the contrary I think the problem is specific to `ppx_blob` and all ppx extensions that would _include_ a file in a source file. The actual compiler invocation has nothing special, it is just that the build system should know there is some additional dependency in that case. But ok, I just wanted to check I had not missed any obvious solution. Thanks!

**Comment by johnwhitington** [comment]
Oh, I understand the question now! I imagine you would have to manually add the dependency.

**Comment by pveber** [comment]
Alright, thanks!
